# Release build script
#
# Uses the common build logic, but also gains capabilities related to releasing the product.

# Only trigger manually
trigger: none
pr: none

pool:
  vmImage: ubuntu-16.04

steps:
# release version should be correctly set in package.json
- bash: |
    PACKAGE_VERSION=$(node -p "require('./package.json').version")
    echo "##vso[build.updatebuildnumber]${PACKAGE_VERSION}"
    echo "$PACKAGE_VERSION" > version.txt
  displayName: Set version number of build

# do all the normal build stuff
- template: common-steps.yml

# if the mini changelog is empty, complain
- bash: |
    LINE_COUNT=$(cat minichangelog.txt | wc -l)
    if [ "$LINE_COUNT" -lt 3 ]; then
      echo Mini changelog is too short. Did you use the wrong version number in CHANGELOG.txt?
      exit 1
    fi
  displayName: Check for length of mini-changelog


# Create a GitHub release
- task: GitHubRelease@0
  inputs:
    gitHubConnection: githubConnection
    repositoryName: '$(Build.Repository.Name)' 
    tagSource: 'manual'
    tag: $(Build.BuildNumber)
    releaseNotesFile: 'minichangelog.txt'
    assets: '$(Build.ArtifactStagingDirectory)/*.vsix'